gettingstarted/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

from first import views as first_views #new


# Examples:
# url(r'^$', 'gettingstarted.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('hello.urls'), name='index'),
    # url(r'^time/now/',first_views.now,name='now'),
    # url(r'^time/meta/',first_views.display_meta,name='meta'),
    # url(r'^time/plus/(\d{1,2})/$',first_views.hours_ahead),
    # url(r'^search/', first_views.search),
    # url(r'^contact_form/',first_views.contact,name='contact'),
    # url(r'^contact_thanks/',first_views.thanks,name='thanks'),
]

hello/urls.py
#coding:utf-8
from django.conf.urls import include, url

from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^db',views.db,name='db'),
	url(r'^book',views.book,name='book'),
	url(r'^blog',views.blog,name='blog'),
	url(r'^record', views.record, name='record'),
	url(r'^',views.index,name='home'),

]

first/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True,verbose_name='e-mail')

    def __str__(self):
        return u'%s %s' % (self.first_name,self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher,on_delete=models.DO_NOTHING)
    publication_date = models.DateField(blank=True,null=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return self.title

hello/models.py
from django.db import models
from first.models import Author
from datetime import datetime
import django.utils.timezone as timezone

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField('date created', auto_now_add=True)


class Blog(models.Model):
    title = models.CharField(max_length=30)
    blog = models.CharField(max_length=32)
    create_time = models.DateTimeField('date created',auto_now_add=True)
    tag = models.CharField(max_length=32)
    author = models.ForeignKey(Author,on_delete=models.DO_NOTHING)

class Record(models.Model):
    date = models.DateTimeField(default=timezone.now,verbose_name='记录时间')
    way = models.CharField(max_length=32,verbose_name="运动方式")
    strength = models.CharField(max_length=64,verbose_name="强度")
    class Meta():
        verbose_name="记录"
        verbose_name_plural="记录"

    def __str__(self):
        return '%s-%s-%s-%s'%(self.way,self.date.year,self.date.month,self.date.day)

first/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message)
        if (num_words <4):
            raise forms.ValidationError("Not enough words!")
        return message

hello/forms.py
from django import forms

class RecordForm(forms.Form):
    way = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'有氧/力量','aria-describedby':'basic-addon1'}))
    strength = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'时间/组数','aria-describedby':'basic-addon2'}))

first/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponse,Http404
from django.core.mail import send_mail
from first.models import Book
from django.http import HttpResponseRedirect
from first.forms import ContactForm

import datetime

def index(request):
    list = "<html><body>now</body></html>"
    return HttpResponse(list)

def now(request):
    now = datetime.datetime.now()
    html = "<html><body>now: %s.</body></html>" % now
    return HttpResponse(html)

def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise  Http404()

    if(offset>=2):
        s = "s"
    else:
        s = ""
    dt = datetime.datetime.now() + datetime.timedelta(hours = offset)
    html = "<html><body>In %s hour%s,it will be %s.</body><html>" %(offset,s,dt)
    return HttpResponse(html)

def display_meta(request):
    values = request.META.items()
    values = sorted(values,key = lambda x:x[0])
    html = []
    for k,v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' %(k,v))
    return HttpResponse('<table>%s</table>'%'\n'.join(html))

def search(request):
    error = []
    if ('q' in request.GET):
        q = request.GET['q']
        if (not q):
            error.append('Enter a search tem.')
        elif len(q) > 20:
            error.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains = q)
            return render_to_response('search_result.html',{'books':books,'query':q})
    return render_to_response('search_form.html', {'error': error})

def contact(request):
    if (request.method == 'POST'):
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email','xxxxxxxxx@qq.com'),
                ['wwwwwww@qq.com']
            )
            return HttpResponseRedirect('/contact_thanks/')
    else:
        form = ContactForm(initial={'subject':'主题'})
    return render(request,'contact_form.html',{'form':form})

def thanks(request):
    return render_to_response('contact_thanks.html')

hello/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
import requests
from .models import Greeting
from first.models import Book
from hello.models import Blog,Record
from .forms import RecordForm
from datetime import datetime
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# Create your views here.
def index(request):
    # return HttpResponse('Hello from Python!')
    return render(request, 'index.html')


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    return render(request, 'db.html', {'greetings': greetings})


def book(request):
    books = Book.objects.all()[::-1]
    paginator = Paginator(books,30.2)
    page = request.GET.get('page')
    try:
        book = paginator.page(page)
    except PageNotAnInteger:
        book = paginator.page(1)
    except EmptyPage:
        book = paginator.page(paginator.num_pages)
    return render(request,'book.html',{"books":books,"book":book})

def book_detail(request):
    d

def blog(request):
    blogs = Blog.objects.all()
    return render(request,'blog.html',locals())

def record(request):
    if(request.method == 'GET'):
        form = RecordForm(request.GET)
        if(form.is_valid()):
            way = form.cleaned_data['way']
            strength = form.cleaned_data['strength']
            record = Record.objects.create(way = way,strength=strength)
            record.save()
            return HttpResponseRedirect('/record/')
    now = datetime.now()
    record = Record.objects.filter(date__year=now.year,date__month=now.month,date__day=now.day)
    form = RecordForm()
    return render(request,'record.html',locals())

first/templates/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }}below
        </p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        <div class="field">
            {{ form.subject.errors }}
            <label for = "id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

first/templates/contact_thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>contact_thanks</title>
</head>
<body>
<p>send email success.</p>
</body>
</html>

first/templates/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    {% if error %}
        <ul>
            {% for error in error %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action = "" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

first/templates/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>search_results</title>
</head>
<body>
<p>You searched for:<strong>{{ query }}</strong></p>
{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}
</body>
</html>

hello/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Index</title>
  <link href="/static/img/favicon.ico" rel="icon" type="image/x-icon" />
  <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/cus.css">
  <script src="/static/js/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="/static/js/bootstrap.js"></script>

</head>

<body >
<header>
<div class="container ">
<nav class="navbar navbar-default navbar-fixed-top ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
   <!--    <a class="navbar-brand" href="/index" style="background-image: url(/static/img/logo.png); width: 50px;"> -->
        <img src="/static/img/logo-1.png" alt="" style="margin-right:15px;padding: 0;">
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Index <span class="sr-only">(current)</span></a></li>
        <li><a href="/record/">Record</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Essay <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/book/">Book</a></li>
            <li><a href="/blog/">Blog</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

<!--   <nav class="navbar navbar-default navbar-fixed-top affix-top">
    <div class="container">
      <div class="navbar-header">
        <a href="#" class="navbar-brand" style="padding: 0;">
          <img src="/static/img/logo.jpg" >
        </a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right" style="margin-top:0">
          <li class="active"><a href="#"><span class="glyphicon glyphicon-home"></span> 首页</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-list"></span> 文章</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-fire"></span> 还没想好</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-question-sign"></span> 关于</a></li>
        </ul> 
      </div>
    </div>
  </nav> -->
</header>
    {% block content %}{% endblock %}

</body>

<footer>


</footer>
</html>

hello/templates/blog.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<div class="table-response">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>#</th>
							<th>Blog</th>
							<th>Tag</th>
							<th>Date</th>
						</tr>
					</thead>
					<tbody>
						{% for blog in blogs %}
                        {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-md-2"></div>
	</div>
</div>

{% endblock %}

hello/templates/book.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4 text-center" >
			<div class="list-group ">
				{% for bk in book %}
	  			<button type="button" class="list-group-item">
				{{ bk.id }}.{{ bk.title }}
	  			</button>
	  			{% endfor %}
			</div>

			<nav aria-label="Page navigation">
			  <ul class="pagination">
                  {% if book.has_previous %}
			    <li>
                    <a href="?page={{ book.previous_page_number }}" aria-label="Previous">
			        <span aria-hidden="true">&laquo;</span>
			      </a>
			    </li>
                  {% endif %}
                {% for pg in book.paginator.page_range %}
                    {% if book.number == pg %}
                    <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                    {% else %}
                    <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                    {% endif %}
                {% endfor %}
              {% if book.has_next %}
                <li><a href="?page={{ book.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a></li>
              {% endif %}
			  </ul>
			</nav>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>
	{% endblock %}

hello/templates/db.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

hello/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="jumbotron">
  <h1>Hello World!</h1>
</div>

{% endblock %}

<div class="container">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/static/img/1.jpg" alt="...">
    </div>
    <div class="item">
      <img src="/static/img/2.jpg" alt="...">
    </div>
    <div class="item">
      <img src="/static/img/3.jpg" alt="...">
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
 </div>
</div>

hello/templates/record.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">添加记录</h4>
            </div>
            <form action="" method="get">
                <div class="modal-body">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">项目</span>
                            {{ form.way }}
{#                            <input type="text" class="form-control" name="way" placeholder="有氧/力量" aria-describedby="basic-addon1">#}
                        </div>
                    <br>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon2">强度</span>
                            {{ form.strength }}
{#                            <input type="text" class="form-control" name="strength" placeholder="时间/组数" aria-describedby="basic-addon2">#}
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class = "container-fluid">
    <div class = "row">
        <div class="col-md-4"></div>
        <div class="col-md-4" >
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">添加记录</button>
            {% for re in record %}
                <ul>
                    <li>{{ re.way }} {{ re.strength }}{{ re.date }}</li>
                </ul>
            {% endfor %}

        </div>
        <div class="col-md-4"></div>
    </div>
</div>

{% endblock %}